import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState} from '../../../app/store';
import { db } from '../../../firebase';
import { cartInfoBox } from '../Type/cartType';

export interface CartSliceType {
  cartInfoBox:cartInfoBox;
}

const initialState: CartSliceType = {
  cartInfoBox:{
    cartInfo:{
      iteminfo:[{
        id:'',
        itemId: 0,
        itemNum: 0,
        itemSize: 0,
        toppings: [],
        }]
      }
  }
};


//ログイン時にカートにデータが残っていたら取得する
export const fetchCart = createAsyncThunk<cartInfoBox,string>(
    'CartSlice/fetchCart',
    async (uid) => {
      const snapShot = await db.collection(`admin/${uid}/orders`).get();
      let cartInfoBox:cartInfoBox = {}
      snapShot.forEach(doc => {
           if(doc.data().status === 0) {
            cartInfoBox.cartInfo = doc.data();
            cartInfoBox.id = doc.id;
           }
      }) 
      // The value we return becomes the `fulfilled` action payload
      return  cartInfoBox;
    }
  );



export const CartSlice = createSlice({
  name: 'cartSlice',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchCart.fulfilled, (state, action) => {
        state.cartInfoBox = action.payload;
      })
  },
});

// export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCartInfoBox = (state: RootState) => state.cartSlice.cartInfoBox;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount: number): AppThunk => (
//   dispatch,
//   getState
// ) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default CartSlice.reducer;
